tali/homepage/urls.py
from django.conf import settings
from django.urls import path, include

from . import views
from django.contrib.auth.views import LogoutView

from rest_framework.routers import DefaultRouter

# adding an app_name makes the below 'names' fall under the namespace polls - e.g polls:index, polls:detail etc.
# when the name is used in templates
app_name = "homepage"

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts, name='posts'),
    path('check_email/', views.check_email, name='check_email'),
    path('activate/<str:pk>', views.TalisActivationView.as_view(), name='activate'),
    path('login/', include('django.contrib.auth.urls')),  
    path('login/logout/', views.do_logout, name='logout'),
    path('login/login/', views.do_logout, name='login'),
]

tali/tali/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

from rest_framework.routers import DefaultRouter
from homepage import views

router = DefaultRouter()
router.register(r'users', views.myUserViewSet, basename='myuser')
router.register(r'posts', views.PostViewSet, basename='Post')


urlpatterns = [
    # path receives 4 args: 'route':str, 'view', 'kwargs':dict, 'name' - unambiguous refrence (see example in polls.urls.py)
    path("", include("homepage.urls")),
    path("admin/", admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

tali/homepage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class myUser(User):
    username = User.email

class Post(models.Model):
    owner = models.ForeignKey('myUser', related_name='posts', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=140, blank=True, default='')
    title = models.CharField(max_length=140, blank=True, default='default title')

tali/homepage/views.py
from django.shortcuts import render
import logging
import os.path

from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django_registration.backends.activation.views import RegistrationView, ActivationView
from django.contrib.auth import login, logout

from rest_framework import viewsets

from homepage.models import myUser, Post
from homepage.serializers import UserSerializer, PostSerializer

from homepage.tasks import add, send_activation_task


SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

def index(request):
    logger = logging.getLogger('logger')
    logger.info(request)

    if request.user.is_authenticated:
        return HttpResponseRedirect('/posts')
    else:
        return render(request, "homepage/index.html", {})
    
def posts(request):

    posts = Post.objects.all().order_by('-created')
    owners = []
    for post in posts:
        print(post.owner.email)
        owners.append(myUser.objects.get(email=post.owner.email))

    posts_and_owners = zip(posts, owners)
    context = {
      'posts_and_owners': posts_and_owners,
    }
    return render(request, "homepage/posts.html", context)


def check_email(request):
    # any + in original email get parsed as white space in the URL - so returning these here
    email = request.GET["email"].replace(' ', '+')
    context = {
        "email": str(email)
    }
    return render(request, "homepage/check_email.html", context)

def do_logout(request):
    if request.user.is_authenticated:
        print("USER IS AUTHENTICATED - LOGGING OUT")
        logout(request)
        return render(request, "homepage/index.html", {})

class MyLoginView(LoginView):

    redirect_authenticated_user = True
    
    def get_success_url(self):
        return render({}, "homepage/index.html", {}) 
    
    def form_invalid(self, form):
        messages.error(self.request,'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class myUserViewSet(viewsets.ModelViewSet):
    queryset = myUser.objects.all()
    serializer_class = UserSerializer

    # overrider the default create method in order to use the builtin 'create_user' function that
    # comes with builtin User. This one hashes the password by itself.
    def create(self, request):
        logger = logging.getLogger('logger')
        logger.info("creating user")
        first_name = request.data["firstname"]
        last_name = request.data["lastname"]
        email = request.data["email"]
        password = request.data["password"]
        username= request.data["username"]
        try:

            logger.info("in try")
            inactive_user = myUser.objects.create_user(
                username=username, 
                email=email, 
                password=password,
                first_name=first_name,
                last_name=last_name,
                is_active=False)
        except Exception as e:
            return HttpResponseBadRequest(e)            
        try:
            logger.info("sending activation")
            send_activation_email(inactive_user)
        except Exception as e:
            return HttpResponseBadRequest(e)

        return HttpResponse()

class TalisActivationView(ActivationView):

    def get(self, request, *args, **kwargs):
        logger = logging.getLogger('poop')
        logger.warning(f'activation view Woot!: {request} {args} {kwargs}')
        kwargs["activation_key"] = kwargs["pk"]
        logger.warning(f'AFTER CHANGE!: {request} {args} {kwargs}')
        activated_user = self.activate(self, *args, **kwargs)
        if activated_user:
            # Step 1:  Login the user
            login(request, activated_user)
        logger.warning(f'USER LOGGED IN!')
        return HttpResponseRedirect('/')
    
from django.views.decorators.csrf import csrf_exempt

class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def perform_create(self, serializer):
        try:
          owner = myUser.objects.get(email=self.request.data.get('owner'))
        except:
            owner = myUser.objects.get(email=self.request.user.email)
        serializer.save(owner=owner)

def send_activation_email(inactive_user: myUser):
    logger = logging.getLogger('logger')
    logger.info("HELLO")
    sender_email = 'tali@skunkworx.co'
    receiver_email = inactive_user.email
    first_name = inactive_user.first_name
    activation_key = RegistrationView().get_activation_key(inactive_user)
    activation_link = 'www.skunkworx.co/activate/{activation_key}'.format(activation_key=activation_key)

    logger = logging.getLogger('activation_email')
    logger.warning(f'activation link is: {activation_link}')
    send_activation_task.delay_on_commit(sender_email, receiver_email, first_name, activation_link)

tali/homepage/templates/homepage/check_email.html
{% load static %}

<head>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script type="text/javascript" src="{% static 'js/js.js' %}"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
    <h1 class="start_section"> Check your email!</h1>
    <p class="start_section"> Activation email sent to:</p> 
    <p>{{ email }}</p>
    <p class="start_section"> Wrong email? <a href="/">Start over</a>. </p>
</body>

tali/homepage/templates/homepage/index.html
{% load static %}

<head>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<script type="text/javascript" src="{% static 'js/signUpController.js' %}"></script>
<script type="text/javascript" src="{% static 'js/js.js' %}"></script>

<!-- Take care of view port zooming for iphone-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>
    if(navigator.userAgent.indexOf('iPhone') > -1 )
{
    document
      .querySelector("[name=viewport]")
      .setAttribute("content","width=device-width, initial-scale=1, maximum-scale=1");
}
</script>
<!-- Take care of view port zooming -->

</head>

<body>

    <div style="width: 100%; height: 30px;"><a style="float: right; margin-right: 10%;"href="{% url 'login' %}">Log in</a> </div>
    <img id="logo" src ="{% static 'img/pepe.jpg' %}" style="display: block; margin: auto; height: 100px; width: 100px;">
    
    <h2> Sign up to SKunKw0rx</h2>
    <form id="signup_form" method="POST" ng-app="signUpApp" ng-controller="signUpCtrl" autocomplete="off">
        {% csrf_token %}
        <input autocomplete="false" name="hidden" type="text" style="display:none;">
        <input type="text" ng-model="firstname" placeholder="first name" required="required" data-lpignore="true">
        <input type="text" ng-model="lastname" placeholder="last name" required="required" data-lpignore="true">
        <input type="email" ng-model="email" placeholder="email address" required="required" data-lpignore="true">
        <input type="password" id="password" ng-model="password" placeholder="create a password" required="required" data-lpignore="true">
        <input type="password" id="password_confirm" ng-model="password_confirm" placeholder="repeat password" required="required" data-lpignore="true" oninput="check()"/>
        <input type="submit" value="Sign up" ng-hide="hide_button" ng-click="signUp($event)">
        <p ng-hide="hide_processing_text" [disabled]="!ngForm.valid"> Signing up (takes a min...)</p>
        <p style="font-size: small; color: red;"ng-bind="error_msg"></p>
    </form>
    <p class="start_section">Already a member? <a href="{% url 'login' %}">Log In</a></p>
    <hr>
    <h2 class="start_section"> About this site</h2>
    <p> This is my Hello World Django site.<br>
        Features: Create  account, write and view posts.<br>
        Mobile friendly, responsive design.<br><br>
        While feature thin, the stack is production ready.<br><br>
        <a class="start_section" href="https://github.com/talisaar/skunkworx/" target=”_blank”>view on Github</a>
    </p>
    <h3 class="start_section"> Tech stack</h3>
    <ul>
    <li>Django on backend</li>
    <li>Angular JS</li>
    <li>Django REST framework</li>
    <li>Served w&#47;Gunicorn & NGINX</li>
    <li>Served from EC2</li>

    <h3 class="start_section"> Other stuff used</h3>

    <li>AWS Route53</li>
    <li>AWS SES</li>
    <li>Rabbitmq & celery queue</li>
    <li>Supervisord & Systemd daemonization</li>
    <li>Postgresql db</li>
    <li>Scss & Compass</li>
    </ul>
    <div id="footer"></div>
</body>

tali/homepage/templates/homepage/posts.html
{% load static %}

<head>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<script type="text/javascript" src="{% static 'js/postController.js' %}"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body ng-app="postApp" ng-controller="postCtrl" autocomplete="off" ng-init="user='{{ user }}'; is_authenticated='{{ user.is_authenticated}}'">

<form id = "logout_form" action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button id="logout_button" type="submit" ng-hide="is_authenticated == 'False'">Log out</button>
    <br>
    <br>
</form>

<p ng-hide="is_authenticated == 'False'">{{ user.first_name }}, post something skunky:</p>

<form id="post_form" method="POST">
    {% csrf_token %}
    <textarea id="post_box" ng-hide="is_authenticated == 'False'" ng-model="post_content_text" name="post_content" form="post_form", placeholder="Write a funny post" maxlength="140"></textarea><br>
    <input id="post_button" type="submit" value="Submit post" ng-hide="is_authenticated == 'False'" ng-hide="hide_button" ng-click="createPost($event)">
</form>
<p ng-hide="is_authenticated == 'True'" style="color:aliceblue"> Please <a href="{% url 'homepage:index' %}">Sign up</a> or <a href="{% url 'login' %}">Log In</a> to write a post </p>

<br>
<br>
<h1>SKunKw0rx feed</h1>
<br>

{% block posts_feed %}
    {% for post, owner in posts_and_owners %}
    <hr>
    <br>
    <p id="post_owner" style="font-size: snall; color: rgb(56, 174, 221);">{{ owner.first_name }} wrote:</p>
    <p id="post_content">{{ post.content }}</p>
    <br>
    {% endfor %}

{% endblock posts_feed %}

<br>
</body>